# Generated by Django 3.2.3 on 2023-07-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='originalName',
        ),
        migrations.AddField(
            model_name='movie',
            name='original_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_name', to='movies.originalname'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director', to='movies.Director'),
        ),
    ]
