# Generated by Django 3.2.3 on 2023-07-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230703_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='movies.originalname'),
        ),
    ]
