# Generated by Django 3.2.3 on 2023-07-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='movies.duration'),
        ),
    ]
