# Generated by Django 3.2.3 on 2023-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='movie', to='movies.Director'),
        ),
    ]
